AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 500

Metrics/BlockLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 15

Naming/MethodName:
  EnforcedStyle: camelCase
