name: Run RSpec tests

on: [push]

jobs:
  run-rspect-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Run tests
        env:
          TEST_SECRET_KEY: $TEST_SECRET_KEY
        run: |
          bundle exec rspec
